title: ""
description: ""
remote_theme: jekyll/minima
markdown: kramdown
header_pages: []
plugins:
  - jekyll-remote-theme
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page
